### ISSUE TITLE
777-300ER wingflex gone

### ISSUE THREAD

**Issue by SGFlightSimmerYT** [NVB9ALT/Realism-pack.#11]
![image](https://user-images.githubusercontent.com/95022255/209955891-dc298060-781a-49b2-bb39-0ecc48b98f47.png)
wingflex on 777 is gone after applying this pack (leading to nav + wing strobes floating)

**Comment by NVB9ALT** [comment]
Watch a) the wingtips and b) the overall curve of the wing very closely. This is actually AriakimTaiyo's realistic wingflex addon, which I've included in the Realism Pack.

[Screen recording 2022-12-29 11.03.40 AM.webm](https://user-images.githubusercontent.com/102188956/209998596-d676085d-5f77-4016-860e-e0a3dbc8cf07.webm)

If the wings don't match the video, then that is indeed an issue.

**Comment by SGFlightSimmerYT** [comment]
the wings didnt flex at all... hmmm

**Comment by NVB9ALT** [comment]
I guess you just can't see it then.
