### ISSUE TITLE
Mismatch of airspeed indicators

### ISSUE THREAD

**Issue by Somnambolist** [NVB9ALT/Realism-pack.#12]
Greetings! 

Great add-on, really love it, thanks!!
I noticed the following issue: (at least) on the Boeing 737, the indicator on the cockpit instrument shows a different airspeed than on the overlay instrument.
![Screenshot_mismatch](https://user-images.githubusercontent.com/122732839/212544270-6f18c24f-3f5d-4727-86e7-06af1c782aa3.png)

To make things even more mysterious: I noticed, when I spawn at the takeoff of a runway, the indicators are in sync, but the speed remains too low (in other words, the value in the overlay instrument remains true (which is too low for the type)). 
However, when I spawn in the air, there is the observed mismatch but the cockpit instrument displays the realistic value.

Not sure what's up there, maybe you can have a look?

Thanks and best regards!!

**Comment by NVB9ALT** [comment]
The overlay indicator uses KCAS, while the cockpit indicators use KIAS (which in GeoFS is equal to KTAS). The reason for this is that if I redefine KIAS to be KCAS, then non-instrument-related animations or effects that use KIAS will no longer work properly. Now that I think about it, though, I might add a UI button to toggle interior instruments to show either KIAS (i.e. KTAS) or KCAS.

Here's the difference in case you don't know:
- KTAS: your speed relative to the air, indicated in knots
- KIAS: your speed relative to the air, divided by the air density in atmospheres (I think, roughly). This means that if you maintain constant KTAS, your KIAS will decrease with altitude. The fun thing about this is that your stall speed in KIAS never changes - you will stall at (for example) 120 KIAS regardless of altitude, however, 120 kias at high altitude is a higher KTAS than at sea level. _In GeoFS, however, KIAS is equal to KTAS._
- KCAS: KCAS is KIAS corrected for errors caused by the position of the pitot probe. In GeoFS, KCAS = true KIAS, if you think about it that way.

Finally, you might be interested to know that the "exterior instruments display KCAS" thing is more or less copy-and-pasted from AP++.

**Comment by Somnambolist** [comment]
Greetings!

 

Ah, thanks, that does it very much for the mismatch between interior and exterior instruments. Thank you very much for the insight!!

 

What I still fail to understand is, why, when spawned at a runway, the internal instruments also shows the lower of the values and the aircraft performance is as if it would fly at the lower speed… Did I miss something there aswell?

(Example: I can spawn at a runway using rightclick and select „GROUND“. When I accelerate I have normal aircraft performance and the mismatch you explained. I can also spawn at the runway using leftclick and the take-off symbol, then both indicators match and the aircraft performance is reduced)

 

Best regards!!

 

Von: NVB9ALT ***@***.***> 
Gesendet: Sonntag, 15. Jänner 2023 19:34
An: NVB9ALT/Realism-pack. ***@***.***>
Cc: Somnambolist ***@***.***>; Author ***@***.***>
Betreff: Re: [NVB9ALT/Realism-pack.] Mismatch of airspeed indicators (Issue #12)

 

The overlay indicator uses KCAS, while the cockpit indicators use KIAS (which in GeoFS is equal to KTAS). The reason for this is that if I redefine KIAS to be KCAS, then non-instrument-related animations or effects that use KIAS will no longer work properly. Now that I think about it, though, I might add a UI button to toggle interior instruments to show either KIAS (i.e. KTAS) or KCAS.

Here's the difference in case you don't know:

*	KTAS: your speed relative to the air, indicated in knots
*	KIAS: your speed relative to the air, divided by the air density in atmospheres (I think, roughly). This means that if you maintain constant KTAS, your KIAS will decrease with altitude. The fun thing about this is that your stall speed in KIAS never changes - you will stall at (for example) 120 KIAS regardless of altitude, however, 120 kias at high altitude is a higher KTAS than at sea level. In GeoFS, however, KIAS is equal to KTAS.
*	KCAS: KCAS is KIAS corrected for errors caused by the position of the pitot probe. In GeoFS, KCAS = true KIAS, if you think about it that way.

Finally, you might be interested to know that the "exterior instruments display KCAS" thing is more or less copy-and-pasted from AP++.

**Comment by NVB9ALT** [comment]
Very strange, I will attempt to replicate this.

**Comment by Somnambolist** [comment]
Hi again!

 

Following my mail to you, I have again tried to replicate… However, I don’t seem to have this issue anymore.

I swear, I do not know what was going on… Yesterday, I was able to reproduce it every time (it even messed up an EXCEL chart I did about climb/sink performance). But I just tried it earlier three times and now it works.

 

Well, I am sorry to have bothered  you… Next time it comes up (if it does) I’ll shoot a video.

 

Again, sorry about that…

 

Best regards!

 

Von: NVB9ALT ***@***.***> 
Gesendet: Sonntag, 15. Jänner 2023 21:05
An: NVB9ALT/Realism-pack. ***@***.***>
Cc: Somnambolist ***@***.***>; Author ***@***.***>
Betreff: Re: [NVB9ALT/Realism-pack.] Mismatch of airspeed indicators (Issue #12)

 

Very strange, I will attempt to replicate this.

**Comment by NVB9ALT** [comment]
When you notice this happening, could you also include a screenshot of the console when this is occurring? There might be some intermittent code error somewhere.

**Comment by Somnambolist** [comment]
Will do!

 

Thanks again!!

And a HAPPY NEW YEAR :).

 

Best regards

 

Von: NVB9ALT ***@***.***> 
Gesendet: Sonntag, 15. Jänner 2023 21:47
An: NVB9ALT/Realism-pack. ***@***.***>
Cc: Somnambolist ***@***.***>; Author ***@***.***>
Betreff: Re: [NVB9ALT/Realism-pack.] Mismatch of airspeed indicators (Issue #12)

 

When you notice this happening, could you also include a screenshot of the console when this is occurring? There might be some intermittent code error somewhere.

**Comment by NVB9ALT** [comment]
I've added the button to toggle between KCAS and KTAS for both interior and exterior instruments.

**Comment by Somnambolist** [comment]
Hi!

 

Thank you!! Awesome!

 

Br, 

Marian

 

Von: NVB9ALT ***@***.***> 
Gesendet: Montag, 6. Februar 2023 19:02
An: NVB9ALT/Realism-pack. ***@***.***>
Cc: Somnambolist ***@***.***>; Author ***@***.***>
Betreff: Re: [NVB9ALT/Realism-pack.] Mismatch of airspeed indicators (Issue #12)

 

I've added the button to toggle between KCAS and KTAS for both interior and exterior instruments.
