### ISSUE TITLE
Lots of errors

### ISSUE THREAD

**Issue by bruhsussy** [NVB9ALT/Realism-pack.#15]
every time I try to run it it gives me errors
![image](https://user-images.githubusercontent.com/115641755/218781081-4f9aa435-3729-44b8-a292-d30bc7a3c669.png)

**Comment by NVB9ALT** [comment]
You don't paste the bookmarklet code into the console, for a start. Also, are you trying to run it via geofs-proxy.coveljulian.repl.co?

**Comment by bruhsussy** [comment]
oh, I'm not. Replit is blocked on my computer. is there any other way to do it?

**Comment by NVB9ALT** [comment]
What method are you currently using to run it?

**Comment by bruhsussy** [comment]
just the normal https://www.geo-fs.com/geofs.php?v=3.5

**Comment by bruhsussy** [comment]
or do you mean bookmarklet?

**Comment by NVB9ALT** [comment]
Yea are you running the bookmarklet right? Because in the screenshot you're copying and pasting it into the console and that's not how you run that.

**Comment by bruhsussy** [comment]
yeah. I copy the text in bookmarklet.js, then make a new bookmark, and make the url the text, then click on the bookmark while in game, right?

**Comment by NVB9ALT** [comment]
yea that's how you run it. If that's what you're doing and it's still erroring, then I'll see if I can fix it. I think I know what the "realismGo is not defined" error is coming from.

**Comment by bruhsussy** [comment]
ok well that was beacuse i was running it in the console. It just doese'nt work when I click the bookmark. I generally test if it's working with the ~ boost

**Comment by bruhsussy** [comment]
so that issue img was just beacuse I was trying to run it on the console.

**Comment by NVB9ALT** [comment]
...the carrier catapults? Those are a little buggy and I need to fix them at some point; they don't always work. A more reliable way is to check if there's a little button in the top right to switch between KIAS and KTAS for your airspeed indicators, or to check if a bunch of credits have been logged in the console.

**Comment by bruhsussy** [comment]
ok.

**Comment by bruhsussy** [comment]
^thats what happens when I click on the bookmark

**Comment by NVB9ALT** [comment]
Thanks for the video; very helpful! I'm gonna test something and if it works, fix the bookmarklet. Gonna need to figure out a way to fix it without someone having to get a new version of the bookmarklet :)

**Comment by bruhsussy** [comment]
cool :) thanks for de help

**Comment by bruhsussy** [comment]
if you could lmk when it is updated that'd be great

**Comment by NVB9ALT** [comment]
try it now, the githack servers should have updated by now

**Comment by bruhsussy** [comment]
oke

**Comment by bruhsussy** [comment]
https://user-images.githubusercontent.com/115641755/218826025-4e05f2ee-3225-4d01-9e2c-43b108bc4c1e.mp4

**Comment by bruhsussy** [comment]
Also I did use the new bookmarklet stuff that you updated

**Comment by NVB9ALT** [comment]
I have no idea what's happening now. It's working fine on geofs-proxy.coveljulian.repl.co (aside from unrelated errors due to beta features I'm testing on it) so...I'll see if I can get Ariakim to look at this.

**Comment by bruhsussy** [comment]
ok. It would be great if it could work on https://www.geo-fs.com/geofs.php?v=3.5 :) tysm for the support

**Comment by Ariakim-Taiyo** [comment]
It's most likely that your school device has disabled bookmarklets.
Since there is no response in the console, the JS is being blocked from running.
I'm not sure how you'd go about running it in that case, That specific 3rd party console can't interface with HTML DOM so all JS elements with click functions will be broken in the best case. I believe there is another one with more functionality, but I forget where it was maintained.

**Comment by bruhsussy** [comment]
ok. one last thing, is there any way to run it using the console?

**Comment by NVB9ALT** [comment]
Well here's the thing - if the school blocks bookmarklets, it should just refuse to run instead of throwing errors like this.

Also, you could probably run the addon by copying and pasting main.js into the console.

**Comment by NVB9ALT** [comment]
Also, isn't that 3rd party console a bookmarklet as well?

**Comment by bruhsussy** [comment]
idk honestly

**Comment by bruhsussy** [comment]
i have it bookmarked

**Comment by bruhsussy** [comment]
will it not work that way?

**Comment by bruhsussy** [comment]
will it not work from a bookmark

**Comment by bruhsussy** [comment]
Because I ran it on the bookmark and it loaded the small button in the top corner but I wasn't able to use like the chat or anything

**Comment by NVB9ALT** [comment]
Oh it works now?

Also yea the addon chat is broken as of a few weeks ago, it'll be temporarily removed with the next update

**Comment by bruhsussy** [comment]
ok cool

**Comment by bruhsussy** [comment]
alright thanks
