### ISSUE TITLE
bugged 737-800

### ISSUE THREAD

**Issue by RuschAirlines** [NVB9ALT/Realism-pack.#16]
I have been running into this problem recently but every time I turn the realism pack on with the 737-800 the cockpit view's windows are really tinted and is basically impossible to fly with.

**Comment by Ariakim-Taiyo** [comment]
The only thing I can think of that would cause this is something in the 737 immersion script. I wrote that for the 737-700, not the -800, so any attempts to apply it to a different aircraft are subject to break, have a lot of issues, or not run at all.

Unfortunately, I can't do anything about it, and I suggest that NVB9 disable the -800 from loading it and see if that helps.

**Comment by kolos26** [comment]
I should try to reduce it to the sound effects, and kinda rewrite it for the -800

**Comment by NVB9ALT** [comment]
I don't think the SFX even apply to the 737-800...piece of crap airplane, I think the cockpit windows are just really dark. Like AriakimTaiyo's CRJ-700 windows _et hem_

**Comment by kolos26** [comment]
Does the script has any effect on the window?

**Comment by Ariakim-Taiyo** [comment]
> Does the script has any effect on the window?

The original script doesn't affect the model at all. Just sounds, flight controls, and animations.

**Comment by kolos26** [comment]
I didn't change that part, so it cannot be caused by this script. I guess, the problem is with the night scenary script, but I had never had this bug using the addon

**Comment by NVB9ALT** [comment]
Nor have I. Besides, I probably need to clean up redundant/ineffective scripts; this addon is basically a pile of code thrown at the DOM.

**Comment by Ariakim-Taiyo** [comment]
That would be the definition of an understatement.

**Comment by NVB9ALT** [comment]
Closed for now because of OP's inactivity.

**Comment by RuschAirlines** [comment]
> @RuschAirlines Can you please send me a screenshot about the dark windows and the console?
this is the bugged version
[](url)
![Geofs complaint](https://user-images.githubusercontent.com/115870907/220269635-75e35704-560e-442d-b4a5-6f889bb0b11f.png) 

this is the normal version

![Geofs complaint 2](https://user-images.githubusercontent.com/115870907/220270342-b91fed92-8611-48f0-a1e7-c92c4fcad2ef.png)

**Comment by NVB9ALT** [comment]
Judging from the screenshots alone, it seems to be the terrain imagery and time of day that causes what you're seeing, not anything with the airplane. If the window's material in the 3d model was darker, the atmosphere would be darker in addition to the ground. See the CRJ-700 cockpit for an example of that.

**Comment by RuschAirlines** [comment]
> Judging from the screenshots alone, it seems to be the terrain imagery and time of day that causes what you're seeing, not anything with the airplane. If the window's material in the 3d model was darker, the atmosphere would be darker in addition to the ground. See the CRJ-700 cockpit for an example of that.

This is exact time and location. 
Without Realism
![Geofs complaint](https://user-images.githubusercontent.com/115870907/220491088-32f19f2f-0fc7-447f-8ef3-6ade4badeffe.png)

With Realism 
![Geofs complaint 2](https://user-images.githubusercontent.com/115870907/220491157-16b9e1f5-5237-47ad-8a40-ad111e534d34.png)

**Comment by NVB9ALT** [comment]
Hopefully fixed now; I did some cleanup and removed a redundant script that barely worked as intended from like six months ago.

**Comment by RuschAirlines** [comment]
> Hopefully fixed now; I did some cleanup and removed a redundant script that barely worked as intended from like six months ago.

Thanks this definitely helped but I found the reason for it being insanely dark was the addon glitches like that with volumetric clouds on.
