### ISSUE TITLE
Spoiler arming dosent work

### ISSUE THREAD

**Issue by Gamer1029384756** [NVB9ALT/Realism-pack.#22]
The spoiler arming dosent work. I have tried shift + b but it dosent work.

**Comment by NVB9ALT** [comment]
Kolos26 is supposedly working on it.

**Comment by Gamer1029384756** [comment]
ok thanks

**Comment by Gamer1029384756** [comment]
Should I close this issue?

**Comment by NVB9ALT** [comment]
Gonna fix it today

**Comment by Gamer1029384756** [comment]
Ok. Thanks.
