### ISSUE TITLE
volumetric clouds issue

### ISSUE THREAD

**Issue by Gamer1029384756** [NVB9ALT/Realism-pack.#23]
When volumetric clouds are enabled, geofs looks like this.
![Screenshot 2023-07-31 163419](https://github.com/NVB9ALT/Realism-pack./assets/136986889/18aab574-69d9-4a98-a539-f840097bad0f)

**Comment by Gamer1029384756** [comment]
this is what the picture looks like without volumetric clouds
![Screenshot 2023-07-31 163805](https://github.com/NVB9ALT/Realism-pack./assets/136986889/471f7057-c066-4a78-bbc1-ee667411ea92)

**Comment by Gamer1029384756** [comment]
I believe it is caused by the g effect unintentionally loading

**Comment by NVB9ALT** [comment]
Yea it's caused by the G effect. Just hit "save and close" in your options panel and then reload GeoFS.

**Comment by Gamer1029384756** [comment]
It worked. Thanks a lot.
