### ISSUE TITLE
Sunrays in the cockpit (suggestion)

### ISSUE THREAD

**Issue by YairGalan** [NVB9ALT/Realism-pack.#3]
It would be cool if something like this is in Geo-FS. It basically is just sunrays in the cockpit, obviously base on the position of the sun. It seems like it would be tough to program, but I imagine the results would be amazing. Love the addon, thanks.

![image](https://user-images.githubusercontent.com/93962160/198067613-d9aa4b9d-26bf-450b-a198-bbf2e57034b7.png)

**Comment by NVB9ALT** [comment]
We already sort of have this in GeoFS - try turning shadows to max and flying in cockpit view.
![Screenshot 2022-10-26 8 41 09 AM](https://user-images.githubusercontent.com/102188956/198072090-05e7c30b-546c-4f81-9e0a-6fcf57f8c46f.png)

**Comment by YairGalan** [comment]
Okay, I didn't realize this, thank you.

**Comment by NVB9ALT** [comment]
That's the brightest as far as I know. However, results may differ depending on how high you can set your graphics.
