### ISSUE TITLE
Runway issues

### ISSUE THREAD

**Issue by KingstonZhu** [NVB9ALT/Realism-pack.#30]
I have tried with both bookmarklet and Tampermonky, but every time, runways look bad. Please fix this issue.

**Comment by NVB9ALT** [comment]
...is this about the runway overlays removal script?

**Comment by Sheppy358** [comment]
NVB9ALT please add the runway overlays

**Comment by NVB9ALT** [comment]
You'll be able to select whether to remove runway overlays or not in the upcoming plugin manager I'm making
