### ISSUE TITLE
Blackout Effect Suggestions

### ISSUE THREAD

**Issue by AbnormalHuman** [NVB9ALT/Realism-pack.#31]
Can we change the blackout effects so it only works if you are on the wings/cockpit view?

**Comment by NVB9ALT** [comment]
Yea I'll probably do that. Makes sense.

**Comment by AbnormalHuman** [comment]
I know it makes sense, because sometimes if people are stunt flying and just black out, then they are flying blind basically.

**Comment by NVB9ALT** [comment]
Done
