### ISSUE TITLE
Suggestion About the Auto-spoiler

### ISSUE THREAD

**Issue by RYANAIR5719** [NVB9ALT/Realism-pack.#34]
Some aircraft have an accessory feature that is activated using the [z] key (e.g., the tail hook on the F-16). Can we change the auto-spoiler so that it is not interfering with the accessory features on planes?

**Comment by NVB9ALT** [comment]
Not gonna lie I _completely_ forgot about this, I'm sorry. I'll fix it.

**Comment by NVB9ALT** [comment]
Fixed, it uses the Shift key now

**Comment by AbnormalHuman** [comment]
Thanks
