### ISSUE TITLE
Replacing the old 737 Immersion SFX script within the pack

### ISSUE THREAD

**Issue by AbnormalHuman** [NVB9ALT/Realism-pack.#37]
I forked a new script from the original and made the GPWS more realistic, and now the alarms only sound in cockpit mode. Thou the "TOO LOW TERRAIN" alarm might be a little bit laggy if descending due to it working for the first time. Anyway, can you please check it out? The link is below:

https://github.com/AbnormalHuman/GeoFS-737-Immersion-SFX

**Comment by NVB9ALT** [comment]
I will when I get my Internet back at home, it's been out of order for five days now and I haven't figured out a way to get my school computer to use addons.

**Comment by NVB9ALT** [comment]
done

**Comment by AbnormalHuman** [comment]
Did you actually tried it???

**Comment by NVB9ALT** [comment]
No but I looked at the code and it seems ok, if you say it works then it probably does work
