### ISSUE TITLE
Pls improve sonic boom.

### ISSUE THREAD

**Issue by GPTbest** [NVB9ALT/Realism-pack.#39]
Yo, I really like this addon but one thing that always bothering me was that the sonic boom wasn't that realistic, I'll give you some points, like when planes touch down in geofs, there will be a smoke, you can probably zoom the smoke and put it onto the plane as a better sonic boom, you can also use this effect as the plane is overloading. And another thing is can you add the livery selector onto the bottom of the screem but not the side, cause I think that would be better, others are ok, pretty nice addon.

**Comment by NVB9ALT** [comment]
what, you want me to make the shock condensation flicker or somth?

also, if you want something to change with the livery selector, go bother Kolos26, he's the one who made it

**Comment by GPTbest** [comment]
yes shock condensation with the smoke that geofs has. ;)

**Comment by GPTbest** [comment]
and pls use the same solution, (the landing smoke)to improve the Wing turbulence of the aircraft

**Comment by NVB9ALT** [comment]
I'll see if I can make it flicker but I'm afraid a smoke emitter is not a realistic-looking way to do this.
