### ISSUE TITLE
Runways are missing

### ISSUE THREAD

**Issue by B-don-don** [NVB9ALT/Realism-pack.#9]
It seems when the code is run, when HD is disabled, runways that are regularly modeled in the simulator are removed.

**Comment by NVB9ALT** [comment]
This is an intentional feature to reduce lag - most runways can be distinguished without the overlays. If you have a list of airports where the runways are hard to distinguish, I'd love to review it.

**Comment by SGFlightSimmerYT** [comment]
but how do i know where to land, for example in KATL the runways are just yellow colour that's it

**Comment by NVB9ALT** [comment]
Circled are the runways themselves and a few identifying details, such as PAPI lights, while arrows point to the thousand-foot markers (touchdown zone markers) and a line highlights the tire marks down the center of the runway. I don't see how distinguishing runways and landing properly on them is difficult.
![Screenshot 2022-12-26 6 52 11 PM](https://user-images.githubusercontent.com/102188956/209604005-e3595f39-c14d-4be1-9d3e-299a246f0f31.png)
